#ifndef FALLING_SANDS_SHORTCUTS
#define FALLING_SANDS_SHORTCUTS

#include <raylib.h>

enum Shortcuts {
  K_PAUSE = KEY_P,
  K_WRITE_MAP = KEY_W,
  K_RESET = KEY_R,
  M_INSERT = MOUSE_LEFT_BUTTON,
  M_REMOVE = MOUSE_RIGHT_BUTTON
};

#endif
